### PR TITLE
refactored tests for ContinuousPrior, updated docs

### PR DESCRIPTION
**Pull request by kkmann**
extended documentation to reflect the fact that both pdf and f
argument to expectation must be VECTORIZED

Tests now more structured / informative on failure

Not ready to merge yet!

### CODE REVIEW

**Comment by kkmann** [comment]
found a problem with the posterior computation: the pdf of the posterior is not properly vectorized 

must be a problem with the pdf of the normal dat distribution

https://github.com/kkmann/otsd/blob/master/R/DataDistribution.R#L86-L90

**Comment by kkmann** [comment]
oh dear, think I found it x)

**Comment by kkmann** [comment]
@MatheMax ifelse() is a bitch, dnorm is properly vectorized but the ifelse clause screwsup vectrization in theta!

https://github.com/kkmann/otsd/blob/c40797087fb0d99b64c355b9e070035673224df7/R/DataDistribution.R#L86-L90

check the docs: https://www.rdocumentation.org/packages/base/versions/3.5.2/topics/ifelse

**Comment by kkmann** [comment]
okay, something is seriously wrong with the continuous posterior computation. I fixed the issue with the fucked up vectorization in DataDistribution / Normal but the posteriors do not make any sense at the moment - they do not converge as expected.
I formulated my expectation in a new test:

https://github.com/kkmann/otsd/blob/e360b78ea03654732017e16a12f4f97746f1dc48/tests/testthat/test_ContinuousPrior.R#L169-L188

the posterior expectation should converge to the true theta if we implemented everything correctly - which it currently does not ;)

**Comment by MatheMax** [comment]
Alright, we worked on the same issue ;)
Are you sure that dnorm is vectorized in the mean?
I will check the posterior computation!

**Comment by kkmann** [comment]
helps if you pass arguments in the right order, think i fixed posteriors.

**Comment by kkmann** [comment]
okay, added a two-arm test but it fails

https://github.com/kkmann/otsd/blob/0619463e057f3faf8dc2baa22d7aeb53f8b0779b/tests/testthat/test_ContinuousPrior.R#L187-L199

@MatheMax can u fix this?

**Comment by kkmann** [comment]
I fixed the two-stage test case, added simulate and fixed more ifelse() errors in #44 

I am closing this since #44 should already build fine.

**Pull request closed without merging**
